[package]
name                      = "common-multipart-rfc7578"
description               = "An implementation of multipart/form-data (RFC7578)"
authors                   = ["Ferris Tseng <ferristseng@fastmail.fm>"]
documentation             = "https://docs.rs/common-multipart-rfc7578"
repository                = "https://github.com/ferristseng/rust-multipart-rfc7578"
keywords                  = ["multipart", "form", "http"]
categories                = ["asynchronous", "web-programming"]
version                   = "0.2.0-rc"
readme                    = "../README.md"
license                   = "MIT OR Apache-2.0"
edition                   = "2018"

[badges]
travis-ci                 = { repository = "ferristseng/rust-multipart-rfc7578" }
maintenance               = { status = "passively-maintained" }

[dependencies]
bytes                     = "0.5"
futures                   = "0.3"
http                      = "0.2"
mime                      = "0.3"
rand                      = "0.5"

[dev-dependencies]
actix-multipart-rfc7578   = { version = "0.3.0-rc", path = "../actix" }
hyper                     = "0.13"
hyper-multipart-rfc7578   = { version = "0.4.0-rc", path = "../hyper" }
