[package]
name                      = "actix-multipart-rfc7578"
description               = "An implementation of multipart/form-data (RFC7578) for Actix"
authors                   = ["Ferris Tseng <ferristseng@fastmail.fm>"]
documentation             = "https://docs.rs/actix-multipart-rfc7578"
repository                = "https://github.com/ferristseng/rust-multipart-rfc7578"
keywords                  = ["actix", "multipart", "form", "http"]
categories                = ["asynchronous", "web-programming"]
version                   = "0.1.0"
readme                    = "../README.md"
license                   = "MIT OR Apache-2.0"

[badges]
travis-ci                 = { repository = "ferristseng/rust-multipart-rfc7578" }
maintenance               = { status = "passively-maintained" }

[dependencies]
actix-web                 = "0.7"
bytes                     = "*"
common-multipart-rfc7578  = { path = "../common" }
futures                   = "*"
